### ISSUE TITLE
Reenable action pdf functionality

### ISSUE THREAD

**Issue by simontegg** [enspiral-dev-academy/twenty-fifty-new-look#14]

**Comment by michael-smith-nz** [comment]
Remove the 'i' link
![screen shot 2015-11-06 at 11 00 26 am](https://cloud.githubusercontent.com/assets/1152577/10983116/b5bc431e-8475-11e5-859f-9b548940b0a5.png)

**Comment by simontegg** [comment]
My Bad. Paul is preparing pdfs for these
